-- =====================================================================================
-- NovaBank - initial schema
--
-- Written in portable SQL so the identical migration runs on PostgreSQL (docker/prod)
-- and H2 (local dev + tests). That is why there are no PostgreSQL ENUM types, no
-- SERIAL, and no vendor-specific functions: enums are VARCHAR + CHECK, and identity
-- columns use the SQL:2003 `GENERATED BY DEFAULT AS IDENTITY` form both engines accept.
-- =====================================================================================

-- -------------------------------------------------------------------------------------
-- users
-- -------------------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     VARCHAR(36)  NOT NULL,
    full_name     VARCHAR(120) NOT NULL,
    email         VARCHAR(160) NOT NULL,
    phone         VARCHAR(20)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    date_of_birth DATE,
    address       VARCHAR(255),
    kyc_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE,
    created_by    VARCHAR(120),
    updated_by    VARCHAR(120),
    CONSTRAINT uk_users_public_id UNIQUE (public_id),
    CONSTRAINT uk_users_email     UNIQUE (email),
    CONSTRAINT ck_users_role      CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

CREATE INDEX idx_users_role ON users (role);

-- -------------------------------------------------------------------------------------
-- accounts
-- -------------------------------------------------------------------------------------
CREATE TABLE accounts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number       VARCHAR(20)   NOT NULL,
    user_id              BIGINT        NOT NULL,
    account_type         VARCHAR(20)   NOT NULL,
    status               VARCHAR(20)   NOT NULL,
    -- NUMERIC, never FLOAT/DOUBLE: binary floating point cannot represent 0.10 exactly,
    -- and accumulated rounding error in a ledger is real money going missing.
    balance              NUMERIC(19, 4) NOT NULL DEFAULT 0,
    currency             VARCHAR(3)     NOT NULL DEFAULT 'INR',
    daily_transfer_limit NUMERIC(19, 4) NOT NULL,
    -- Optimistic-locking counter maintained by Hibernate's @Version.
    version              BIGINT         NOT NULL DEFAULT 0,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE,
    created_by           VARCHAR(120),
    updated_by           VARCHAR(120),
    CONSTRAINT uk_accounts_number   UNIQUE (account_number),
    CONSTRAINT fk_accounts_user     FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_accounts_type     CHECK (account_type IN ('SAVINGS', 'CURRENT', 'FIXED_DEPOSIT')),
    CONSTRAINT ck_accounts_status   CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED')),
    CONSTRAINT ck_accounts_currency CHECK (currency IN ('INR', 'USD', 'EUR', 'GBP'))
);

CREATE INDEX idx_accounts_owner  ON accounts (user_id);
CREATE INDEX idx_accounts_status ON accounts (status);

-- -------------------------------------------------------------------------------------
-- transactions  (append-only ledger)
-- -------------------------------------------------------------------------------------
CREATE TABLE transactions (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Shared by both legs of a transfer: this is what links the debit to its credit.
    reference               VARCHAR(36)    NOT NULL,
    account_id              BIGINT         NOT NULL,
    counterparty_account_id BIGINT,
    transaction_type        VARCHAR(20)    NOT NULL,
    direction               VARCHAR(10)    NOT NULL,
    amount                  NUMERIC(19, 4) NOT NULL,
    balance_after           NUMERIC(19, 4) NOT NULL,
    status                  VARCHAR(10)    NOT NULL,
    description             VARCHAR(255),
    category                VARCHAR(60),
    -- Nullable, but unique when present: this index is what makes a retried transfer
    -- impossible to apply twice, even if two requests race past the service-level check.
    idempotency_key         VARCHAR(80),
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE,
    created_by              VARCHAR(120),
    updated_by              VARCHAR(120),
    CONSTRAINT fk_tx_account       FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_tx_counterparty  FOREIGN KEY (counterparty_account_id) REFERENCES accounts (id),
    CONSTRAINT uk_tx_idempotency   UNIQUE (idempotency_key),
    CONSTRAINT ck_tx_amount        CHECK (amount > 0),
    CONSTRAINT ck_tx_direction     CHECK (direction IN ('CREDIT', 'DEBIT')),
    CONSTRAINT ck_tx_status        CHECK (status IN ('SUCCESS', 'FAILED', 'REVERSED')),
    CONSTRAINT ck_tx_type          CHECK (transaction_type IN
        ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER_OUT', 'TRANSFER_IN', 'INTEREST_CREDIT', 'FEE'))
);

-- Composite index matching the statement query's WHERE + ORDER BY, so paging through
-- history is an index range scan rather than a full sort of the table.
CREATE INDEX idx_tx_account_created ON transactions (account_id, created_at DESC);
CREATE INDEX idx_tx_reference       ON transactions (reference);
CREATE INDEX idx_tx_created         ON transactions (created_at);

-- -------------------------------------------------------------------------------------
-- beneficiaries
-- -------------------------------------------------------------------------------------
CREATE TABLE beneficiaries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id       BIGINT       NOT NULL,
    account_number VARCHAR(20)  NOT NULL,
    nickname       VARCHAR(120) NOT NULL,
    holder_name    VARCHAR(120) NOT NULL,
    bank_name      VARCHAR(120),
    is_favourite   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE,
    created_by     VARCHAR(120),
    updated_by     VARCHAR(120),
    CONSTRAINT fk_beneficiary_owner       FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT uk_beneficiary_owner_account UNIQUE (owner_id, account_number)
);

CREATE INDEX idx_beneficiary_owner ON beneficiaries (owner_id);

-- -------------------------------------------------------------------------------------
-- refresh_tokens  (server-side revocation list for JWT sessions)
-- -------------------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- SHA-256 of the token, never the token itself.
    token_hash VARCHAR(128) NOT NULL,
    user_id    BIGINT       NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_refresh_user    ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_expires ON refresh_tokens (expires_at);

-- -------------------------------------------------------------------------------------
-- audit_logs  (append-only)
-- -------------------------------------------------------------------------------------
CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor       VARCHAR(160) NOT NULL,
    action      VARCHAR(60)  NOT NULL,
    entity_type VARCHAR(60),
    entity_id   VARCHAR(60),
    detail      VARCHAR(1000),
    ip_address  VARCHAR(60),
    outcome     VARCHAR(10)  NOT NULL DEFAULT 'SUCCESS',
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_created ON audit_logs (created_at);
CREATE INDEX idx_audit_actor   ON audit_logs (actor);
CREATE INDEX idx_audit_action  ON audit_logs (action);
